### ISSUE TITLE
Make all failed

### ISSUE THREAD

**Issue by dvitcompte** [neuronic-ai/autogpt-ui#4]
Hello,

I tried to "sudo make all" the last version, but with no success.
Here is the error : 

![error](https://github.com/neuronic-ai/autogpt-ui/assets/17274434/0ab7cbc8-9f5a-48df-b9ae-971599f1f4c8)

Dockerfile reference : 
https://github.com/neuronic-ai/autogpt-ui/blob/117b3e39a16d64b4811a99bf6905649d91230c66/backend/Dockerfile#L36

My .env file content : 
![env file](https://github.com/neuronic-ai/autogpt-ui/assets/17274434/62204014-27e1-4235-b4f9-e3629f61a453)

Could you help me to fix it ?

Regards,

**Comment by Yolley** [comment]
Thank you for reporting, missed the `AUTO_GPT_VERSION` arg in docker-compose file. Added, please pull the latest version.
